# ==========================================
# TEMPLATE GITHUB ACTIONS - DEPLOY AUTOMÁTICO
# ==========================================
#
# Como usar este template:
#
# 1. Copiar este arquivo para: .github/workflows/deploy-producao.yml
# 2. Substituir as variáveis abaixo com os valores do seu projeto
# 3. Configurar o secret SSH_PRIVATE_KEY no GitHub
# 4. Fazer commit e push
#
# ==========================================

name: Deploy Produção

on:
  push:
    branches:
      - main  # OU master - verificar qual é a branch principal
  workflow_dispatch:

env:
  # ====================================
  # ⬇️ CONFIGURAR ESTAS VARIÁVEIS ⬇️
  # ====================================

  PROJECT_NAME: NOME_DO_PROJETO          # Ex: code-erp, multt, emprestimo
  SERVER_HOST: SEU_SERVIDOR.com.br       # Ex: code-erp.appjvs.com.br
  SERVER_USER: root                       # Usuário SSH (geralmente root)
  TOMCAT_PATH: /root/appservers/apache-tomcat-9/webapps/NOME_DO_PROJETO

  # Arquivo que contém a versão (geralmente src/producao.properties)
  VERSION_FILE: src/producao.properties

  # ====================================
  # ⬆️ FIM DAS CONFIGURAÇÕES ⬆️
  # ====================================

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Ler versão
        id: version
        run: |
          VERSION=$(grep -oP 'versao=\K.*' ${{ env.VERSION_FILE }})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=producao-$VERSION" >> $GITHUB_OUTPUT
          echo "📦 Versão: $VERSION"

      - name: Compilar projeto
        run: |
          echo "🔨 Compilando..."

          if [ -f .classpath ]; then
            sed -i 's/including="\*\*\/\*.java"//g' .classpath
          fi

          mvn clean install -U -DskipTests

          if [ ! -d "target/${{ env.PROJECT_NAME }}-1.0" ]; then
            echo "❌ Erro na compilação"
            exit 1
          fi

          echo "✅ Compilação OK"

      - name: Preparar artefatos
        run: |
          cd target/${{ env.PROJECT_NAME }}-1.0
          tar -czf ../${{ env.PROJECT_NAME }}.tar.gz .

      - name: Criar tag
        run: |
          TAG="${{ steps.version.outputs.tag }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -d $TAG 2>/dev/null || true
          git push origin :refs/tags/$TAG 2>/dev/null || true
          git tag -a $TAG -m "Release $TAG - $(date +"%d-%m-%Y")"
          git push origin $TAG
          echo "✅ Tag $TAG criada"

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Backup no servidor
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'ENDSSH'
            BACKUP_DIR="/root/backups/${{ env.PROJECT_NAME }}"
            mkdir -p $BACKUP_DIR
            DATE=$(date +"%Y%m%d_%H%M%S")

            if [ -d "${{ env.TOMCAT_PATH }}" ]; then
              cd ${{ env.TOMCAT_PATH }}/..
              tar -czf $BACKUP_DIR/backup_$DATE.tar.gz ${{ env.PROJECT_NAME }}
              cd $BACKUP_DIR
              ls -t backup_*.tar.gz | tail -n +6 | xargs -r rm
              echo "✅ Backup criado"
            fi
ENDSSH

      - name: Parar Tomcat
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'ENDSSH'
            # Para o Tomcat usando o script personalizado
            /root/tomcat.sh stop

            # Aguarda até 30 segundos para garantir que parou
            for i in {1..30}; do
              if ! pgrep -f "tomcat" > /dev/null; then
                echo "✅ Tomcat parado"
                exit 0
              fi
              sleep 1
            done

            # Se ainda estiver rodando, força a parada
            pkill -9 -f "tomcat" || true
            sleep 2
ENDSSH

      - name: Deploy
        run: |
          scp target/${{ env.PROJECT_NAME }}.tar.gz \
            ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:/tmp/

          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'ENDSSH'
            rm -rf ${{ env.TOMCAT_PATH }}
            mkdir -p ${{ env.TOMCAT_PATH }}
            cd ${{ env.TOMCAT_PATH }}
            tar -xzf /tmp/${{ env.PROJECT_NAME }}.tar.gz
            rm /tmp/${{ env.PROJECT_NAME }}.tar.gz
            chown -R root:root ${{ env.TOMCAT_PATH }}
            echo "✅ Deploy OK"
ENDSSH

      - name: Iniciar Tomcat
        run: |
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} << 'ENDSSH'
            rm -f /root/appservers/apache-tomcat-9/logs/catalina.out

            # Inicia Tomcat usando o script personalizado
            /root/tomcat.sh start

            # Aguarda inicialização
            for i in {1..60}; do
              if grep -q "Server startup in" /root/appservers/apache-tomcat-9/logs/catalina.out 2>/dev/null; then
                echo "✅ Tomcat iniciado!"
                exit 0
              fi

              if grep -q "SEVERE" /root/appservers/apache-tomcat-9/logs/catalina.out 2>/dev/null; then
                echo "❌ Erro no Tomcat"
                tail -n 50 /root/appservers/apache-tomcat-9/logs/catalina.out
                exit 1
              fi

              sleep 1
            done

            echo "⚠️ Timeout"
            exit 1
ENDSSH

      - name: Verificar aplicação
        run: |
          sleep 10
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.SERVER_HOST }}/ || echo "000")

          if [ "$HTTP_CODE" -eq 200 ] || [ "$HTTP_CODE" -eq 302 ]; then
            echo "✅ App OK (HTTP $HTTP_CODE)"
          else
            echo "⚠️ HTTP $HTTP_CODE"
          fi

      - name: Sucesso
        if: success()
        run: |
          echo "✅ Deploy v${{ steps.version.outputs.version }} OK!"
          echo "🏷️ Tag: ${{ steps.version.outputs.tag }}"
          echo "🌐 https://${{ env.SERVER_HOST }}/"
